name: Publish CI
on:
  release:
    types: [published]
jobs:
  push_to_registries:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build TypeScript
        run: npm run build
      - name: Run tests
        run: npm run test
      - name: Authentication npm
        uses: jgierer12/npm-auth-gpr@v1
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Publish to npm
        run: npm publish
